"""Package spectral/ for the browser and write web/src/generated/build-info.json.

    python web/scripts/build_py_archive.py

Works from any working directory; needs only NumPy (no PyQt).

Writes
  web/public/py/spectral-<sha256[:12]>.zip
      every spectral/**/*.py (sorted, fixed timestamps, no __pycache__) plus a
      generated spectral/_build_info.py holding SOURCE_REVISION. Older
      spectral-*.zip files in that folder are removed.
  web/src/generated/build-info.json
      sourceRevision, archive {file, sha256, bytes}, pinned Pyodide, expected
      runtime versions, presets (spectral.browser.presets_json()), and
      presetValidation: the convergence record of every preset x outer sign,
      computed natively through spectral.browser.run so the page can skip the
      2x check for them.
"""

from __future__ import annotations

import hashlib
import io
import json
import platform
import time
import zipfile

from _common import REPO_ROOT, WEB_DIR, source_revision, spectral_sources, use_revision

PYODIDE_VERSION = "314.0.7"
PYODIDE_INDEX_URL = f"https://cdn.jsdelivr.net/pyodide/v{PYODIDE_VERSION}/full/"
EXPECTED_RUNTIME = {"python": "3.14.2", "numpy": "2.4.6"}

_ZIP_DATE = (1980, 1, 1, 0, 0, 0)


def _archive_bytes(revision: str) -> tuple[bytes, list[str]]:
    entries = dict(spectral_sources())     # the same files source_revision() hashes
    entries["spectral/_build_info.py"] = (
        '"""Generated by web/scripts/build_py_archive.py; exists only in the web '
        'archive."""\n\n'
        f"SOURCE_REVISION = {revision!r}\n"
    ).encode("utf-8")
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for name in sorted(entries):
            info = zipfile.ZipInfo(name, date_time=_ZIP_DATE)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.create_system = 3                  # unix, so attrs are portable
            info.external_attr = 0o100644 << 16
            zf.writestr(info, entries[name], compresslevel=9)
    return buf.getvalue(), sorted(entries)


def _preset_validation() -> dict:
    import spectral.browser as browser
    from spectral.maxwell.presets import PRESETS

    out = {}
    for name, params in PRESETS.items():
        for sign in (1, -1):
            p = dict(params)
            p["outer_sign"] = sign
            meta_json, psi = browser.run(json.dumps(p), None, None)
            meta = json.loads(meta_json)
            if not meta["ok"]:
                raise SystemExit(f"preset {name!r} outer_sign {sign:+d} failed: "
                                 f"{meta['error']}")
            q = meta["quadrature"]
            print(f"  {name[:36]:36s} {sign:+d}  {q['status']:8s} n_quad "
                  f"{q['used_n_quad']:4d} vs {q['check_n_quad']:4d}: "
                  f"{q['discrepancy_rel_peak']:.2e}")
            out[meta["config_key"]] = browser.validation_record(meta)
    return out


def main() -> int:
    t0 = time.perf_counter()
    revision = source_revision()
    use_revision(revision)
    import numpy as np
    import spectral.browser as browser

    data, names = _archive_bytes(revision)
    sha = hashlib.sha256(data).hexdigest()
    py_dir = WEB_DIR / "public" / "py"
    py_dir.mkdir(parents=True, exist_ok=True)
    fname = f"spectral-{sha[:12]}.zip"
    removed = []
    for old in py_dir.glob("spectral-*.zip"):
        if old.name != fname:
            old.unlink()
            removed.append(old.name)
    (py_dir / fname).write_bytes(data)

    print(f"source revision {revision}")
    print(f"archive py/{fname}: {len(names)} files, {len(data):,} bytes, sha256 {sha}")
    if removed:
        print(f"removed stale: {', '.join(removed)}")
    print(f"preset validation (native Python {platform.python_version()}, "
          f"NumPy {np.__version__}):")
    validation = _preset_validation()

    info = {
        "sourceRevision": revision,
        "archive": {"file": f"py/{fname}", "sha256": sha, "bytes": len(data)},
        "pyodide": {"version": PYODIDE_VERSION, "indexURL": PYODIDE_INDEX_URL},
        "expected": EXPECTED_RUNTIME,
        "presets": json.loads(browser.presets_json()),
        "presetValidation": validation,
    }
    gen_dir = WEB_DIR / "src" / "generated"
    gen_dir.mkdir(parents=True, exist_ok=True)
    out = gen_dir / "build-info.json"
    out.write_text(json.dumps(info, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {out.relative_to(REPO_ROOT).as_posix()} ({len(validation)} validation "
          f"records) in {time.perf_counter() - t0:.1f} s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
